### ISSUE TITLE
PlatformException(EQ, No equalizer found, null)

### ISSUE THREAD

**Issue by murugadossp** [rohansohonee/equalizer#1]
**Describe the bug**
Equalizer.open always throwing exception as
PlatformException(EQ, No equalizer found, null)
Audiosessionid is passed correctly.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Android version 10

``` 

**Additional context**
Add any other context about the problem here.

**Comment by rohansohonee** [comment]
@murugadossp 

I have addressed this bug by returning the future for `Equalizer.open(audioSessionId)` function. You can refer to the updated example [here](https://github.com/rohansohonee/equalizer/blob/master/example/lib/main.dart).
>If your device supports equalizer functionality, but the plugin reports `No equalizer found!`, please share further information by completing the bug report.

**Comment by murugadossp** [comment]
try {
                await Equalizer.open(audioSessionId);
              }catch(exception){
                print("Exception Occurred: $exception");
              }
                print("After setupEqualizer()");
              }
Above is the code: still experiencing same issue.

**Comment by rohansohonee** [comment]
The plugin was unable to find an Equalizer for your device. Can you verify that the device you are running has support for Equalizer. You could do this by opening Google Play Music/YouTube Music and head over to settings and then equaliser. If it opens the device equaliser, then I will look into this further. Please share more information by refilling the existing report.

**Comment by UwaisWisitech** [comment]
How you get the audioSessionId? 
Please help.

**Comment by rohansohonee** [comment]
@UwaisWisitech 

You can refer to the docs: https://developer.android.com/reference/android/media/MediaPlayer#getAudioSessionId()
The just_audio plugin on pub.dev provides this sessionId. If you are using another plugin for audio do check the API for a sessionId.

**Comment by UwaisWisitech** [comment]
> @UwaisWisitech
> 
> You can refer to the docs: https://developer.android.com/reference/android/media/MediaPlayer#getAudioSessionId()
> The just_audio plugin on pub.dev provides this sessionId. If you are using another plugin for audio do check the API for a sessionId.

Thanks @rohansohonee
